name: Publish apk to GitHub Packages
on:
  push:
    tags:
      - "v*"
jobs:
  apk:
    name: Release MiniDroid APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate Debug APK
        run: ./gradlew clean assembleDebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release and Upload debug APK
        uses: underwindfall/create-release-with-debugapk@v1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Minima-${{ steps.get_version.outputs.VERSION }}.apk
          asset_content_type: application/zip
          draft: false
          prerelease: true